### ISSUE TITLE
Migrate Looking Glass to Ahmesen domain

### ISSUE THREAD

**Issue by MeesJ** [ZT-E/Looking-Glass#1]
On 18 October 2022, the `zt-e.tech` domain name will be departed. @Ahmesen/ise, please migrate Looking Glass to any official Ahmesen domain asap.

**Comment by HYP3RDRIVES** [comment]
It always has been on .cachical.com domains for months now

**Comment by MeesJ** [comment]
README.md suggests otherwise
![](https://user-images.githubusercontent.com/77725857/196644295-6d2dd6bf-3a53-499f-87cb-938346232372.png)
