### ISSUE TITLE
Looking Glass inaccessible

### ISSUE THREAD

**Issue by MeesJ** [ZT-E/Looking-Glass#2]
The looking glass endpoints under https://lhr.cachical.com are inaccessible and return a 404.
![](https://user-images.githubusercontent.com/77725857/229840196-4022fa74-78e8-44f8-8c2c-2e1f9e22c2ec.png)

The index of the looking glass domain doesn't return any errors but also doesn't result an expected result either.
![](https://user-images.githubusercontent.com/77725857/229840355-74caf478-fbc9-477f-81c6-1d3b5dc2372d.png)

**Comment by HYP3RDRIVES** [comment]
Resolved

Furthermore this is an internal node/deployment issue not a issue with the code itself so does not belong here.
